//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 UsbControl.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_USBCONTROL_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_DLG_VIDEO                   129
#define IDC_BTN_OPENUSB                 1000
#define IDC_BTN_OPENFILE                1001
#define IDC_STATIC_TEXT                 1003
#define IDC_CHECK1                      1004
#define IDC_BTN_OPENUSB2                1004
#define IDC_BTN_VIDEOCAPTURE            1004
#define IDC_STC_VIDEO                   1005
#define IDC_BTN_VIDEOCAPTURE2           1005
#define IDC_BTN_STOPCAPTURE             1005
#define IDC_BTN_SAVE                    1006
#define IDC_BTN_SNAP                    1006
#define IDC_RADIO_NEWDRIVER             1007
#define IDC_BTN_READDEV                 1007
#define IDC_BTN_CONNECT                 1007
#define IDC_RADIO_OLDDRIVER             1008
#define IDC_BTN_SEARCH                  1008
#define IDC_RADIO_NORMAL                1009
#define IDC_RADIO_XMIRROR               1010
#define IDC_RADIO_YMIRROR               1011
#define IDC_RADIO_XYMIRROR              1012
#define IDC_BTN_REVIEW                  1013
#define IDC_BTN_CLOSECON                1013
#define IDC_RADIO_NORMAL_CHANGE         1014
#define IDC_BTN_SNAP2                   1014
#define IDC_RADIO_RG_CHANGE             1015
#define IDC_RADIO_RB_CHANGE             1016
#define IDC_RADIO_GB_CHANGE             1017
#define IDC_BUTTON_TRIG                 1018
#define IDC_EDIT1                       1019
#define IDC_EDITA                       1019
#define IDC_EDIT2                       1020
#define IDC_EDITB                       1020
#define IDC_BUTTON_SETIP                1021
#define IDC_BUTTON3                     1022
#define IDC_PipeReset                   1022
#define IDC_BUTTON_CAM_ORDER            1022
#define IDC_BUTTON_SENDexpo             1022
#define IDC_tbAddr                      1023
#define IDC_BUTTON_SENDgain             1023
#define IDC_tbData                      1024
#define IDC_BUTTON_SENDgain2            1024
#define IDC_text1                       1025
#define IDC_BUTTON_SENDcamsize          1025
#define IDC_text2                       1026
#define IDC_BUTTON_ForceIp              1026
#define IDC_I2CRead                     1027
#define IDC_EDITC                       1027
#define IDC_I2CWrite                    1028
#define IDC_COMBO1                      1028
#define IDC_COMBO_CHANNEL               1028
#define IDC_PipeReset2                  1029
#define IDC_btnDeviceReset              1029
#define IDC_CHECK_SAVE                  1029
#define IDC_IPADDRESS_GATE              1030
#define IDC_IPADDRESS_GATE2             1031
#define IDC_IPADDRESS_CAM               1032
#define IDC_EDIT_PACK                   1033
#define IDC_EDIT_bgain                  1033
#define IDC_EDIT_INTV                   1034
#define IDC_EDIT_regaddr                1034
#define IDC_EDIT_EXPO                   1035
#define IDC_EDIT_GAIN                   1036
#define IDC_IPADDRESS_SUBNET            1037
#define IDC_EDIT_REG__ADDR              1038
#define IDC_EDIT_rgain                  1038
#define IDC_STATIC_PACK                 1039
#define IDC_STATIC_TRIG                 1040
#define IDC_EDIT_TrigFreq               1041
#define IDC_COMBO_TRIG                  1042
#define IDC_STATIC_PACK2                1043
#define IDC_BTN_TRIG                    1044
#define IDC_BTN_WBSet                   1045
#define IDC_EDITMAXP                    1045
#define IDC_BTNW                        1046
#define IDC_EDITCAMSIZE                 1047
#define IDC_EDIT_regdata                1047
#define IDC_EDIT_ggain                  1048
#define IDC_LIST1                       1049
#define IDC_EDIT_ggain2                 1050
#define IDC_CHECK_Gain                  1051
#define IDC_CHECK_EXPO                  1052
#define IDC_static_imgctrl              1053
#define IDC_BTNregread                  1054
#define IDC_BTNregwrite                 1055
#define IDC_EDIT_camsize                1056
#define IDC_EDIT_roixstart              1057
#define IDC_EDIT_roixend                1058
#define IDC_EDIT_roiystart              1059
#define IDC_EDIT_roiyend                1060
#define IDC_CHECK_roienable             1061
#define IDC_CHECK_binning               1062
#define IDC_CHECK_skip                  1063
#define IDC_BTN_WBSet2                  1064
#define IDC_IPADDRESS_CAM2              1065
#define IDC_IPADDRESS_PCIP              1065
#define IDC_IPADDRESS_CAM3              1066
#define IDC_IPADDRESS_SUBNET2           1067
#define IDC_IPADDRESS_PCIP2             1068
#define IDC_BTN_roiset                  1069
#define btn_test                        1070
#define IDC_BTN_TRIG2                   1071
#define IDC_EDITMAXW                    1072
#define btn_test2                       1072
#define btn_resolu                      1072
#define IDC_EDITMINW                    1073
#define IDC_CHECK_MAC                   1074

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
